/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Estructior
 */
public class myForm extends javax.swing.JFrame {

    koneksi connect = new koneksi();
    ResultSet data = null;

    /**
     * Creates new form myForm
     */
    public myForm() {
        initComponents();
        setTitle("Ujian Praktek");
      }

    private void refresh() {

        int jumbaris = 0;
        int i = 0;

        String query = "select * from mahasiswa";

        try {
            data = connect.getStatement().executeQuery(query);
            while (data.next()) {
                jumbaris++;
            }
        } catch (SQLException ex) {

        }
        String isi[][] = new String[jumbaris][6];

        try {
            data = connect.getStatement().executeQuery(query);
            while (data.next()) {
                isi[i][0] = data.getString("npm");
                isi[i][1] = data.getString("nama");
                isi[i][2] = data.getString("uts");
                isi[i][3] = data.getString("uas");
                isi[i][4] = data.getString("nilai");
                i++;
            }
        } catch (SQLException ex) {

        }
        String namakolom[] = {"npm", "nama", "uts", "uas", "nilai"};
        DefaultTableModel model = new DefaultTableModel(isi, namakolom) {
        };
        tblmahasiswa.setModel(model);
        
    }
    
    private String getNilai(int uts, int uas) {
        double total = ((0.7 * uts) + (0.3 * uas));
        
        if (total >= 90) {
            return "A";
        } else if (total < 90 && total >= 80) {
            return "B";
        } else if (total < 80 && total >= 70) {
            return "C";
        } else if (total < 70 && total >= 60) {
            return "D";
        } else {
            return "E"; 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tambah_npm_label = new javax.swing.JLabel();
        tambah_nama_label = new javax.swing.JLabel();
        tambah_uts_label = new javax.swing.JLabel();
        tambah_uas_label = new javax.swing.JLabel();
        txtTambahNPM = new javax.swing.JTextField();
        txtTambahNama = new javax.swing.JTextField();
        txtTambahUTS = new javax.swing.JTextField();
        txtTambahUAS = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btncarimahasiswa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtnpmupdate = new javax.swing.JTextField();
        btncariupdate = new javax.swing.JButton();
        txtnamaupdate = new javax.swing.JTextField();
        txtutsupdate = new javax.swing.JTextField();
        txtuasupdate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtnpmhapus = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmahasiswa = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tambah_npm_label.setText("NPM");

        tambah_nama_label.setText("NAMA");

        tambah_uts_label.setText("UTS");

        tambah_uas_label.setText("UAS");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambah_uts_label)
                    .addComponent(tambah_uas_label)
                    .addComponent(tambah_nama_label)
                    .addComponent(tambah_npm_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTambahNPM, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(txtTambahNama)
                    .addComponent(txtTambahUAS)
                    .addComponent(txtTambahUTS))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambah_npm_label)
                    .addComponent(txtTambahNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah_nama_label)
                    .addComponent(txtTambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah_uts_label)
                    .addComponent(txtTambahUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah_uas_label)
                    .addComponent(txtTambahUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTambah)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tambah Mahasiswa", jPanel1);

        jLabel6.setText("NPM");

        btncarimahasiswa.setText("Cari");
        btncarimahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarimahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtcari, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btncarimahasiswa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncarimahasiswa)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cari Mahasiswa", jPanel2);

        jLabel9.setText("NPM");

        btncariupdate.setText("Cari");
        btncariupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariupdateActionPerformed(evt);
            }
        });

        txtnamaupdate.setEnabled(false);

        txtutsupdate.setEnabled(false);

        txtuasupdate.setEnabled(false);

        jLabel11.setText("Nama");

        jLabel12.setText("UTS");

        jLabel13.setText("UAS");

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtutsupdate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamaupdate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnpmupdate)
                            .addComponent(txtuasupdate, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btncariupdate))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtnpmupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncariupdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtutsupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuasupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(btnupdate)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Mahasiswa", jPanel5);

        jLabel7.setText("NPM");

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtnpmhapus))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnhapus)
                        .addGap(0, 435, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnpmhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapus)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hapus Mahasiswa", jPanel3);

        tblmahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmahasiswa.setEnabled(false);
        jScrollPane2.setViewportView(tblmahasiswa);

        btnrefresh.setText("Refresh Table");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnrefresh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed

        String npm = txtTambahNPM.getText();
        String nama = txtTambahNama.getText();
        int uts = Integer.parseInt(txtTambahUTS.getText());
        int uas = Integer.parseInt(txtTambahUAS.getText());
        String nilai = getNilai(uts, uas);

        String query = "insert into mahasiswa(npm, nama, uts, uas, nilai) values('" + npm + "','" + nama + 
                "'," + uts + "," + uas + ",'" + nilai + "')";

        try {
            connect.getStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Insert berhasil");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Insert gagal");
        }
    
        refresh();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed

        refresh();
      
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btncarimahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarimahasiswaActionPerformed
        String kode = txtcari.getText();

        int jumbaris = 0;
        int i = 0;

        String query = "select * from mahasiswa where npm='" + kode + "'";

        try {
            data = connect.getStatement().executeQuery(query);
            while (data.next()) {
                jumbaris++;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "data tidak ditemukan");
        }
        String isi[][] = new String[jumbaris][5];

        try {
            data = connect.getStatement().executeQuery(query);

            while (data.next()) {
                isi[i][0] = data.getString("npm");
                isi[i][1] = data.getString("nama");
                isi[i][2] = data.getString("uts");
                isi[i][3] = data.getString("uas");
                isi[i][4] = data.getString("nilai");
                i++;
            }

        } catch (SQLException ex) {

        }
        String namakolom[] = {"npm", "nama", "uts", "uas", "nilai"};
        DefaultTableModel model = new DefaultTableModel(isi, namakolom) {
        };
        tblmahasiswa.setModel(model);

    }//GEN-LAST:event_btncarimahasiswaActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String npm = txtnpmhapus.getText();
        String nama, harga, stok;

        String query = "delete from mahasiswa where npm='" + npm + "'";
        try {
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Ingin dihapus?");

            switch (konfirmasi) {
                case 0:
                    connect.getStatement().executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "data tidak ditemukan");
        }
        refresh();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncariupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariupdateActionPerformed
        String npm = txtnpmupdate.getText();
        String nama, uts, uas;

        String query = "select * from mahasiswa where npm='" + npm + "'";

        try {
            data = connect.getStatement().executeQuery(query);
            if (data.next()) {
                nama = data.getString("nama");
                uts = data.getString("uts");
                uas = data.getString("uas");

                txtnamaupdate.setText(nama);
                txtutsupdate.setText(uts);
                txtuasupdate.setText(uas);

                txtnamaupdate.setEnabled(true);
                txtutsupdate.setEnabled(true);
                txtuasupdate.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "data tidak ditemukan");
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_btncariupdateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String npm = txtnpmupdate.getText();
        String nama = txtnamaupdate.getText();
        int uts = Integer.parseInt(txtutsupdate.getText());
        int uas = Integer.parseInt(txtuasupdate.getText());
        String nilai = getNilai(uts, uas);
        
        txtnamaupdate.setEnabled(false);
        txtutsupdate.setEnabled(false);
        txtuasupdate.setEnabled(false);

        String query = "update mahasiswa set nama='" + nama + "', uts=" + uts + ",uas=" + uas + 
                ",nilai='" + nilai + "' where npm='" + npm + "'";
        try {
            connect.getStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(null, "update berhasil");
        } catch (SQLException ex) {

        }
        refresh();
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btncarimahasiswa;
    private javax.swing.JButton btncariupdate;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tambah_nama_label;
    private javax.swing.JLabel tambah_npm_label;
    private javax.swing.JLabel tambah_uas_label;
    private javax.swing.JLabel tambah_uts_label;
    private javax.swing.JTable tblmahasiswa;
    private javax.swing.JTextField txtTambahNPM;
    private javax.swing.JTextField txtTambahNama;
    private javax.swing.JTextField txtTambahUAS;
    private javax.swing.JTextField txtTambahUTS;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnamaupdate;
    private javax.swing.JTextField txtnpmhapus;
    private javax.swing.JTextField txtnpmupdate;
    private javax.swing.JTextField txtuasupdate;
    private javax.swing.JTextField txtutsupdate;
    // End of variables declaration//GEN-END:variables
}
